# Generated by Django 4.0.6 on 2024-04-01 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificate',
            name='link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
